### ISSUE TITLE
Fix namespaces and psr compliance

### ISSUE THREAD

**Issue by italeks** [daveross/functional-programming-utils#3]
@daveross 
Hey, I like the project and wanna help, I can fix namespaces mostly when
```php
/*
* @return Closure
*/
```
should be 
```php
/*
* @return \Closure
*/
```
So IDE know it's from global namespace.
and also indentation according to PSR since it's I guess most popular standard theses days.
Can you add me to contributors so I could create PRs.
Thanks.

**Comment by daveross** [comment]
This should be completely addressed in version 4.0.0. Let me know if you see additional changes that will make it work better with your IDE.
